/**
 * Mock data para Reports: Margens, Comissões e ABC clientes (§10.16, §10.19).
 */

// ─── Margens ──────────────────────────────────────────────────────────────────

export type MarginClassification = 'A' | 'B' | 'C' | 'D';

export interface CustomerMarginRow {
  id: string;
  name: string;
  revenueEur: number;
  cogsEur: number;
  marginEur: number;
  marginPct: number;
  classification: MarginClassification;
}

export interface ProductMarginRow {
  id: string;
  sku: string;
  name: string;
  category: string;
  revenueEur: number;
  cogsEur: number;
  marginEur: number;
  marginPct: number;
}

export interface CategoryMarginRow {
  category: string;
  revenueEur: number;
  cogsEur: number;
  marginEur: number;
  marginPct: number;
}

export const mockCustomerMargins: CustomerMarginRow[] = [
  {
    id: 'c001',
    name: 'Flor da Vila — Lisboa',
    revenueEur: 42800,
    cogsEur: 24100,
    marginEur: 18700,
    marginPct: 43.7,
    classification: 'A',
  },
  {
    id: 'c002',
    name: 'Rosas do Norte — Porto',
    revenueEur: 38500,
    cogsEur: 22400,
    marginEur: 16100,
    marginPct: 41.8,
    classification: 'A',
  },
  {
    id: 'c003',
    name: 'Jardim Secreto — Braga',
    revenueEur: 31200,
    cogsEur: 19800,
    marginEur: 11400,
    marginPct: 36.5,
    classification: 'A',
  },
  {
    id: 'c004',
    name: 'Pétalas & Arte — Coimbra',
    revenueEur: 27600,
    cogsEur: 17900,
    marginEur: 9700,
    marginPct: 35.1,
    classification: 'B',
  },
  {
    id: 'c005',
    name: 'Verde Vivo — Setúbal',
    revenueEur: 24300,
    cogsEur: 16100,
    marginEur: 8200,
    marginPct: 33.7,
    classification: 'B',
  },
  {
    id: 'c006',
    name: 'Bouquet Clássico — Faro',
    revenueEur: 21900,
    cogsEur: 14800,
    marginEur: 7100,
    marginPct: 32.4,
    classification: 'B',
  },
  {
    id: 'c007',
    name: 'Estúdio Botânico — Évora',
    revenueEur: 19400,
    cogsEur: 13600,
    marginEur: 5800,
    marginPct: 29.9,
    classification: 'B',
  },
  {
    id: 'c008',
    name: 'Flores do Alentejo — Beja',
    revenueEur: 17200,
    cogsEur: 12400,
    marginEur: 4800,
    marginPct: 27.9,
    classification: 'C',
  },
  {
    id: 'c009',
    name: 'Artfloral — Viseu',
    revenueEur: 15800,
    cogsEur: 11700,
    marginEur: 4100,
    marginPct: 25.9,
    classification: 'C',
  },
  {
    id: 'c010',
    name: 'Natureza Viva — Leiria',
    revenueEur: 14500,
    cogsEur: 10900,
    marginEur: 3600,
    marginPct: 24.8,
    classification: 'C',
  },
  {
    id: 'c011',
    name: 'Casa das Flores — Santarém',
    revenueEur: 12300,
    cogsEur: 9600,
    marginEur: 2700,
    marginPct: 21.9,
    classification: 'C',
  },
  {
    id: 'c012',
    name: 'Floral Design — Aveiro',
    revenueEur: 11100,
    cogsEur: 8900,
    marginEur: 2200,
    marginPct: 19.8,
    classification: 'C',
  },
  {
    id: 'c013',
    name: 'Raízes & Ramos — Viana',
    revenueEur: 9800,
    cogsEur: 8100,
    marginEur: 1700,
    marginPct: 17.3,
    classification: 'D',
  },
  {
    id: 'c014',
    name: 'Girassol — Guimarães',
    revenueEur: 8400,
    cogsEur: 7200,
    marginEur: 1200,
    marginPct: 14.3,
    classification: 'D',
  },
  {
    id: 'c015',
    name: 'Mimosa Shop — Castelo Branco',
    revenueEur: 6900,
    cogsEur: 6300,
    marginEur: 600,
    marginPct: 8.7,
    classification: 'D',
  },
];

export const mockProductMargins: ProductMarginRow[] = [
  {
    id: 'p001',
    sku: 'LAV-001',
    name: 'Lavanda francesa seca (maço 30 hastes)',
    category: 'Lavanda',
    revenueEur: 18600,
    cogsEur: 8200,
    marginEur: 10400,
    marginPct: 55.9,
  },
  {
    id: 'p002',
    sku: 'PAM-001',
    name: 'Pampilho seco premium',
    category: 'Gramíneas',
    revenueEur: 14200,
    cogsEur: 6800,
    marginEur: 7400,
    marginPct: 52.1,
  },
  {
    id: 'p003',
    sku: 'HEL-002',
    name: 'Helichrysum laranja (caixa 50 maços)',
    category: 'Imortelas',
    revenueEur: 12800,
    cogsEur: 6400,
    marginEur: 6400,
    marginPct: 50.0,
  },
  {
    id: 'p004',
    sku: 'NIK-001',
    name: 'Nigella orientalis seca',
    category: 'Nigella',
    revenueEur: 9400,
    cogsEur: 4900,
    marginEur: 4500,
    marginPct: 47.9,
  },
  {
    id: 'p005',
    sku: 'CRY-001',
    name: 'Cristal grass preservado',
    category: 'Gramíneas',
    revenueEur: 8100,
    cogsEur: 4400,
    marginEur: 3700,
    marginPct: 45.7,
  },
  {
    id: 'p006',
    sku: 'RSA-003',
    name: 'Rosa seca premium vermelha (cx 100)',
    category: 'Rosas',
    revenueEur: 22400,
    cogsEur: 12600,
    marginEur: 9800,
    marginPct: 43.8,
  },
  {
    id: 'p007',
    sku: 'EUR-001',
    name: 'Eucalipto preservado (ramo)',
    category: 'Folhagens',
    revenueEur: 11200,
    cogsEur: 6500,
    marginEur: 4700,
    marginPct: 41.9,
  },
  {
    id: 'p008',
    sku: 'STY-001',
    name: 'Statice branca seca',
    category: 'Statice',
    revenueEur: 7300,
    cogsEur: 4500,
    marginEur: 2800,
    marginPct: 38.4,
  },
  {
    id: 'p009',
    sku: 'ACR-001',
    name: 'Açafroeira seca laranja',
    category: 'Imortelas',
    revenueEur: 6800,
    cogsEur: 4300,
    marginEur: 2500,
    marginPct: 36.8,
  },
  {
    id: 'p010',
    sku: 'LAG-001',
    name: 'Lagurus ovatus seco (maço)',
    category: 'Gramíneas',
    revenueEur: 5900,
    cogsEur: 3900,
    marginEur: 2000,
    marginPct: 33.9,
  },
  {
    id: 'p011',
    sku: 'PEO-001',
    name: 'Peónia seca rosa claro',
    category: 'Peónias',
    revenueEur: 16800,
    cogsEur: 11600,
    marginEur: 5200,
    marginPct: 30.9,
  },
  {
    id: 'p012',
    sku: 'GYP-001',
    name: 'Gipsófila seca (cx 10 maços)',
    category: 'Gipsófila',
    revenueEur: 8400,
    cogsEur: 6100,
    marginEur: 2300,
    marginPct: 27.4,
  },
  {
    id: 'p013',
    sku: 'CAL-001',
    name: 'Calathea preservada',
    category: 'Folhagens',
    revenueEur: 7100,
    cogsEur: 5200,
    marginEur: 1900,
    marginPct: 26.8,
  },
  {
    id: 'p014',
    sku: 'SUN-002',
    name: 'Girassol seco (cx 20)',
    category: 'Girassóis',
    revenueEur: 11400,
    cogsEur: 8600,
    marginEur: 2800,
    marginPct: 24.6,
  },
  {
    id: 'p015',
    sku: 'BAS-001',
    name: 'Basket grass seco',
    category: 'Gramíneas',
    revenueEur: 4200,
    cogsEur: 3200,
    marginEur: 1000,
    marginPct: 23.8,
  },
  {
    id: 'p016',
    sku: 'RSA-001',
    name: 'Rosa seca branca (cx 100)',
    category: 'Rosas',
    revenueEur: 19800,
    cogsEur: 15400,
    marginEur: 4400,
    marginPct: 22.2,
  },
  {
    id: 'p017',
    sku: 'PRO-001',
    name: 'Protea seca natural',
    category: 'Proteas',
    revenueEur: 13600,
    cogsEur: 10800,
    marginEur: 2800,
    marginPct: 20.6,
  },
  {
    id: 'p018',
    sku: 'CED-001',
    name: 'Cedro azul preservado',
    category: 'Folhagens',
    revenueEur: 6200,
    cogsEur: 5000,
    marginEur: 1200,
    marginPct: 19.4,
  },
  {
    id: 'p019',
    sku: 'AMM-001',
    name: 'Ammi majus seco',
    category: 'Silvestres',
    revenueEur: 4800,
    cogsEur: 3900,
    marginEur: 900,
    marginPct: 18.8,
  },
  {
    id: 'p020',
    sku: 'BUN-001',
    name: 'Bunny tails seco (maço 30)',
    category: 'Gramíneas',
    revenueEur: 5100,
    cogsEur: 4300,
    marginEur: 800,
    marginPct: 15.7,
  },
];

export const mockCategoryMargins: CategoryMarginRow[] = [
  { category: 'Lavanda', revenueEur: 32400, cogsEur: 14800, marginEur: 17600, marginPct: 54.3 },
  { category: 'Gramíneas', revenueEur: 28600, cogsEur: 14900, marginEur: 13700, marginPct: 47.9 },
  { category: 'Imortelas', revenueEur: 24100, cogsEur: 13200, marginEur: 10900, marginPct: 45.2 },
  { category: 'Rosas', revenueEur: 48200, cogsEur: 29400, marginEur: 18800, marginPct: 39.0 },
  { category: 'Folhagens', revenueEur: 21800, cogsEur: 14400, marginEur: 7400, marginPct: 33.9 },
  { category: 'Peónias', revenueEur: 18900, cogsEur: 13600, marginEur: 5300, marginPct: 28.0 },
];

// ─── Comissões ────────────────────────────────────────────────────────────────

export type CommissionBasis = 'MARGIN' | 'REVENUE';

export interface CommissionRow {
  salesRep: string;
  month: string; // YYYY-MM
  basis: CommissionBasis;
  pct: number; // percentage, e.g. 5 for 5%
  baseEur: number;
  commissionEur: number;
  ordersCount: number;
  frozen: boolean;
}

export const mockCommissions: CommissionRow[] = [
  // Ana Santos
  {
    salesRep: 'Ana Santos',
    month: '2025-12',
    basis: 'MARGIN',
    pct: 6,
    baseEur: 38400,
    commissionEur: 2304,
    ordersCount: 42,
    frozen: true,
  },
  {
    salesRep: 'Ana Santos',
    month: '2026-01',
    basis: 'MARGIN',
    pct: 6,
    baseEur: 41200,
    commissionEur: 2472,
    ordersCount: 45,
    frozen: true,
  },
  {
    salesRep: 'Ana Santos',
    month: '2026-02',
    basis: 'MARGIN',
    pct: 6,
    baseEur: 39800,
    commissionEur: 2388,
    ordersCount: 43,
    frozen: true,
  },
  {
    salesRep: 'Ana Santos',
    month: '2026-03',
    basis: 'MARGIN',
    pct: 6,
    baseEur: 44600,
    commissionEur: 2676,
    ordersCount: 48,
    frozen: true,
  },
  {
    salesRep: 'Ana Santos',
    month: '2026-04',
    basis: 'MARGIN',
    pct: 6,
    baseEur: 46100,
    commissionEur: 2766,
    ordersCount: 51,
    frozen: true,
  },
  {
    salesRep: 'Ana Santos',
    month: '2026-05',
    basis: 'MARGIN',
    pct: 6,
    baseEur: 28300,
    commissionEur: 1698,
    ordersCount: 29,
    frozen: false,
  },
  // Bruno Ferreira
  {
    salesRep: 'Bruno Ferreira',
    month: '2025-12',
    basis: 'REVENUE',
    pct: 2.5,
    baseEur: 62100,
    commissionEur: 1553,
    ordersCount: 58,
    frozen: true,
  },
  {
    salesRep: 'Bruno Ferreira',
    month: '2026-01',
    basis: 'REVENUE',
    pct: 2.5,
    baseEur: 68400,
    commissionEur: 1710,
    ordersCount: 63,
    frozen: true,
  },
  {
    salesRep: 'Bruno Ferreira',
    month: '2026-02',
    basis: 'REVENUE',
    pct: 2.5,
    baseEur: 65200,
    commissionEur: 1630,
    ordersCount: 61,
    frozen: true,
  },
  {
    salesRep: 'Bruno Ferreira',
    month: '2026-03',
    basis: 'REVENUE',
    pct: 2.5,
    baseEur: 71800,
    commissionEur: 1795,
    ordersCount: 67,
    frozen: true,
  },
  {
    salesRep: 'Bruno Ferreira',
    month: '2026-04',
    basis: 'REVENUE',
    pct: 2.5,
    baseEur: 74200,
    commissionEur: 1855,
    ordersCount: 69,
    frozen: true,
  },
  {
    salesRep: 'Bruno Ferreira',
    month: '2026-05',
    basis: 'REVENUE',
    pct: 2.5,
    baseEur: 44100,
    commissionEur: 1103,
    ordersCount: 41,
    frozen: false,
  },
  // Catarina Lopes
  {
    salesRep: 'Catarina Lopes',
    month: '2025-12',
    basis: 'MARGIN',
    pct: 5,
    baseEur: 22600,
    commissionEur: 1130,
    ordersCount: 28,
    frozen: true,
  },
  {
    salesRep: 'Catarina Lopes',
    month: '2026-01',
    basis: 'MARGIN',
    pct: 5,
    baseEur: 24800,
    commissionEur: 1240,
    ordersCount: 31,
    frozen: true,
  },
  {
    salesRep: 'Catarina Lopes',
    month: '2026-02',
    basis: 'MARGIN',
    pct: 5,
    baseEur: 23100,
    commissionEur: 1155,
    ordersCount: 29,
    frozen: true,
  },
  {
    salesRep: 'Catarina Lopes',
    month: '2026-03',
    basis: 'MARGIN',
    pct: 5,
    baseEur: 26400,
    commissionEur: 1320,
    ordersCount: 33,
    frozen: true,
  },
  {
    salesRep: 'Catarina Lopes',
    month: '2026-04',
    basis: 'MARGIN',
    pct: 5,
    baseEur: 27900,
    commissionEur: 1395,
    ordersCount: 35,
    frozen: true,
  },
  {
    salesRep: 'Catarina Lopes',
    month: '2026-05',
    basis: 'MARGIN',
    pct: 5,
    baseEur: 16200,
    commissionEur: 810,
    ordersCount: 20,
    frozen: false,
  },
];

export const COMMISSION_MONTHS = ['2025-12', '2026-01', '2026-02', '2026-03', '2026-04', '2026-05'];

// ─── ABC clientes ──────────────────────────────────────────────────────────────

export interface AbcCustomerRow {
  id: string;
  name: string;
  region: string;
  revenueEur: number;
  marginEur: number;
  marginPct: number;
  bucket: MarginClassification;
  previousBucket?: MarginClassification;
}

export const mockAbcCustomers: AbcCustomerRow[] = [
  // Bucket A — top 20%
  {
    id: 'a001',
    name: 'Flor da Vila — Lisboa',
    region: 'Lisboa',
    revenueEur: 42800,
    marginEur: 18700,
    marginPct: 43.7,
    bucket: 'A',
  },
  {
    id: 'a002',
    name: 'Rosas do Norte — Porto',
    region: 'Porto',
    revenueEur: 38500,
    marginEur: 16100,
    marginPct: 41.8,
    bucket: 'A',
  },
  {
    id: 'a003',
    name: 'Jardim Secreto — Braga',
    region: 'Braga',
    revenueEur: 31200,
    marginEur: 11400,
    marginPct: 36.5,
    bucket: 'A',
  },
  {
    id: 'a004',
    name: 'AlvesFlor — Lisboa',
    region: 'Lisboa',
    revenueEur: 29800,
    marginEur: 10900,
    marginPct: 36.6,
    bucket: 'A',
  },
  {
    id: 'a005',
    name: 'Botânica Sul — Setúbal',
    region: 'Setúbal',
    revenueEur: 28100,
    marginEur: 10200,
    marginPct: 36.3,
    bucket: 'A',
  },
  {
    id: 'a006',
    name: 'Studio Verde — Porto',
    region: 'Porto',
    revenueEur: 27600,
    marginEur: 9700,
    marginPct: 35.1,
    bucket: 'A',
  },
  {
    id: 'a007',
    name: 'Florada — Cascais',
    region: 'Lisboa',
    revenueEur: 26400,
    marginEur: 9200,
    marginPct: 34.8,
    bucket: 'A',
  },
  {
    id: 'a008',
    name: 'Alma Floral — Sintra',
    region: 'Lisboa',
    revenueEur: 24900,
    marginEur: 8600,
    marginPct: 34.5,
    bucket: 'A',
  },
  // Bucket B — 20-50%
  {
    id: 'b001',
    name: 'Pétalas & Arte — Coimbra',
    region: 'Coimbra',
    revenueEur: 27600,
    marginEur: 9700,
    marginPct: 35.1,
    bucket: 'B',
    previousBucket: 'A',
  },
  {
    id: 'b002',
    name: 'Verde Vivo — Setúbal',
    region: 'Setúbal',
    revenueEur: 24300,
    marginEur: 8200,
    marginPct: 33.7,
    bucket: 'B',
    previousBucket: 'A',
  },
  {
    id: 'b003',
    name: 'Bouquet Clássico — Faro',
    region: 'Algarve',
    revenueEur: 21900,
    marginEur: 7100,
    marginPct: 32.4,
    bucket: 'B',
  },
  {
    id: 'b004',
    name: 'Estúdio Botânico — Évora',
    region: 'Alentejo',
    revenueEur: 19400,
    marginEur: 5800,
    marginPct: 29.9,
    bucket: 'B',
  },
  {
    id: 'b005',
    name: 'MFlor — Viana do Castelo',
    region: 'Braga',
    revenueEur: 18200,
    marginEur: 5400,
    marginPct: 29.7,
    bucket: 'B',
  },
  {
    id: 'b006',
    name: 'Jardins do Minho — Braga',
    region: 'Braga',
    revenueEur: 17600,
    marginEur: 5100,
    marginPct: 29.0,
    bucket: 'B',
  },
  {
    id: 'b007',
    name: 'Floricenter — Aveiro',
    region: 'Aveiro',
    revenueEur: 16800,
    marginEur: 4700,
    marginPct: 28.0,
    bucket: 'B',
  },
  {
    id: 'b008',
    name: 'Blossom — Lisboa',
    region: 'Lisboa',
    revenueEur: 16100,
    marginEur: 4400,
    marginPct: 27.3,
    bucket: 'B',
  },
  {
    id: 'b009',
    name: 'Raízes — Guarda',
    region: 'Guarda',
    revenueEur: 15400,
    marginEur: 4200,
    marginPct: 27.3,
    bucket: 'B',
  },
  {
    id: 'b010',
    name: 'Roseira — Coimbra',
    region: 'Coimbra',
    revenueEur: 14900,
    marginEur: 3900,
    marginPct: 26.2,
    bucket: 'B',
  },
  {
    id: 'b011',
    name: 'Terra Floral — Leiria',
    region: 'Leiria',
    revenueEur: 14200,
    marginEur: 3700,
    marginPct: 26.1,
    bucket: 'B',
  },
  {
    id: 'b012',
    name: 'Silvestres — Porto',
    region: 'Porto',
    revenueEur: 13800,
    marginEur: 3500,
    marginPct: 25.4,
    bucket: 'B',
  },
  // Bucket C — 50-80%
  {
    id: 'c001',
    name: 'Flores do Alentejo — Beja',
    region: 'Alentejo',
    revenueEur: 17200,
    marginEur: 4800,
    marginPct: 27.9,
    bucket: 'C',
  },
  {
    id: 'c002',
    name: 'Artfloral — Viseu',
    region: 'Viseu',
    revenueEur: 15800,
    marginEur: 4100,
    marginPct: 25.9,
    bucket: 'C',
  },
  {
    id: 'c003',
    name: 'Natureza Viva — Leiria',
    region: 'Leiria',
    revenueEur: 14500,
    marginEur: 3600,
    marginPct: 24.8,
    bucket: 'C',
  },
  {
    id: 'c004',
    name: 'Casa das Flores — Santarém',
    region: 'Santarém',
    revenueEur: 12300,
    marginEur: 2700,
    marginPct: 21.9,
    bucket: 'C',
  },
  {
    id: 'c005',
    name: 'Floral Design — Aveiro',
    region: 'Aveiro',
    revenueEur: 11100,
    marginEur: 2200,
    marginPct: 19.8,
    bucket: 'C',
  },
  {
    id: 'c006',
    name: 'Botanika — Porto',
    region: 'Porto',
    revenueEur: 10800,
    marginEur: 2100,
    marginPct: 19.4,
    bucket: 'C',
  },
  {
    id: 'c007',
    name: 'Floriarte — Funchal',
    region: 'Madeira',
    revenueEur: 10200,
    marginEur: 1900,
    marginPct: 18.6,
    bucket: 'C',
  },
  {
    id: 'c008',
    name: 'Pétala Branca — Faro',
    region: 'Algarve',
    revenueEur: 9600,
    marginEur: 1700,
    marginPct: 17.7,
    bucket: 'C',
  },
  {
    id: 'c009',
    name: 'Amora Floral — Setúbal',
    region: 'Setúbal',
    revenueEur: 9100,
    marginEur: 1500,
    marginPct: 16.5,
    bucket: 'C',
  },
  {
    id: 'c010',
    name: 'Azul Floral — Ponta Delgada',
    region: 'Açores',
    revenueEur: 8600,
    marginEur: 1300,
    marginPct: 15.1,
    bucket: 'C',
  },
  {
    id: 'c011',
    name: 'Flor do Campo — Viseu',
    region: 'Viseu',
    revenueEur: 8200,
    marginEur: 1200,
    marginPct: 14.6,
    bucket: 'C',
  },
  {
    id: 'c012',
    name: 'Estação das Flores — Lisboa',
    region: 'Lisboa',
    revenueEur: 7800,
    marginEur: 1100,
    marginPct: 14.1,
    bucket: 'C',
  },
  // Bucket D — bottom 20%
  {
    id: 'd001',
    name: 'Raízes & Ramos — Viana',
    region: 'Braga',
    revenueEur: 9800,
    marginEur: 1700,
    marginPct: 17.3,
    bucket: 'D',
  },
  {
    id: 'd002',
    name: 'Girassol — Guimarães',
    region: 'Braga',
    revenueEur: 8400,
    marginEur: 1200,
    marginPct: 14.3,
    bucket: 'D',
  },
  {
    id: 'd003',
    name: 'Mimosa Shop — Castelo Branco',
    region: 'Castelo Branco',
    revenueEur: 6900,
    marginEur: 600,
    marginPct: 8.7,
    bucket: 'D',
  },
  {
    id: 'd004',
    name: 'Florimax — Portalegre',
    region: 'Alentejo',
    revenueEur: 6100,
    marginEur: 500,
    marginPct: 8.2,
    bucket: 'D',
  },
  {
    id: 'd005',
    name: 'Naturalis — Bragança',
    region: 'Trás-os-Montes',
    revenueEur: 5400,
    marginEur: 400,
    marginPct: 7.4,
    bucket: 'D',
  },
  {
    id: 'd006',
    name: 'Flor do Vale — Chaves',
    region: 'Trás-os-Montes',
    revenueEur: 4800,
    marginEur: 300,
    marginPct: 6.3,
    bucket: 'D',
  },
  {
    id: 'd007',
    name: 'Campestre — Miranda do Douro',
    region: 'Trás-os-Montes',
    revenueEur: 3900,
    marginEur: 200,
    marginPct: 5.1,
    bucket: 'D',
  },
  {
    id: 'd008',
    name: 'Silene — Évora',
    region: 'Alentejo',
    revenueEur: 3200,
    marginEur: 100,
    marginPct: 3.1,
    bucket: 'D',
  },
];
