/**
 * Dados mock para o módulo Visitas.
 */

export type VisitStatus =
  | 'PLANNED'
  | 'CONFIRMED'
  | 'IN_PROGRESS'
  | 'DONE'
  | 'NO_SHOW'
  | 'CANCELLED';

export interface MockVisit {
  id: string;
  customerId: string;
  customerName: string;
  city: string;
  country: 'PT' | 'ES';
  scheduledAt: string;
  completedAt?: string;
  status: VisitStatus;
  salesRep: string;
  notes: string;
  geo: { lat: number; lng: number };
}

// ---------------------------------------------------------------------------
// Helpers de data (relativos a 2026-05-13)
// ---------------------------------------------------------------------------
function daysFromNow(d: number, h = 10, m = 0): string {
  const dt = new Date('2026-05-13T00:00:00Z');
  dt.setDate(dt.getDate() + d);
  dt.setHours(h, m, 0, 0);
  return dt.toISOString();
}

function daysAgo(d: number, h = 10, m = 0): string {
  return daysFromNow(-d, h, m);
}

// ---------------------------------------------------------------------------
// Visitas: 15 futuras (próximos 30d) + 20 históricas (últimos 90d)
// ---------------------------------------------------------------------------
export const mockVisits: MockVisit[] = [
  // ---- Futuras (15) --------------------------------------------------------
  {
    id: 'VIS-2026-001',
    customerId: 'CUS-101',
    customerName: 'Floricultura Lurdes',
    city: 'Porto',
    country: 'PT',
    scheduledAt: daysFromNow(1, 9, 0),
    status: 'CONFIRMED',
    salesRep: 'Tiago Sousa',
    notes: 'Apresentar nova coleção verão. Levar amostras Pampas e Ruscus tingido.',
    geo: { lat: 41.1579, lng: -8.6291 },
  },
  {
    id: 'VIS-2026-002',
    customerId: 'CUS-102',
    customerName: 'Atelier Flora Coimbra',
    city: 'Coimbra',
    country: 'PT',
    scheduledAt: daysFromNow(2, 10, 30),
    status: 'CONFIRMED',
    salesRep: 'Ana Martins',
    notes: 'Renovação de contrato anual. Trazer proposta de condições comerciais.',
    geo: { lat: 40.2033, lng: -8.4103 },
  },
  {
    id: 'VIS-2026-003',
    customerId: 'CUS-103',
    customerName: 'Jardim Secreto Braga',
    city: 'Braga',
    country: 'PT',
    scheduledAt: daysFromNow(3, 11, 0),
    status: 'PLANNED',
    salesRep: 'Pedro Silva',
    notes: 'Primeiro contacto presencial. Lead vindo da Expoflora.',
    geo: { lat: 41.5518, lng: -8.4229 },
  },
  {
    id: 'VIS-2026-004',
    customerId: 'CUS-104',
    customerName: 'Daisy Florist Porto',
    city: 'Porto',
    country: 'PT',
    scheduledAt: daysFromNow(4, 14, 0),
    status: 'PLANNED',
    salesRep: 'Tiago Sousa',
    notes: 'Seguimento ao catálogo enviado por email.',
    geo: { lat: 41.1496, lng: -8.6109 },
  },
  {
    id: 'VIS-2026-005',
    customerId: 'CUS-105',
    customerName: 'Florama Viseu',
    city: 'Viseu',
    country: 'PT',
    scheduledAt: daysFromNow(5, 10, 0),
    status: 'CONFIRMED',
    salesRep: 'Pedro Silva',
    notes: 'Visita agendada por email. Pedro apresenta linha premium.',
    geo: { lat: 40.6566, lng: -7.9122 },
  },
  {
    id: 'VIS-2026-006',
    customerId: 'CUS-106',
    customerName: 'Verde Naranja Madrid',
    city: 'Madrid',
    country: 'ES',
    scheduledAt: daysFromNow(7, 9, 30),
    status: 'CONFIRMED',
    salesRep: 'Tiago Sousa',
    notes: 'Reunião pós-reclamação. Apresentar plano de melhoria de qualidade.',
    geo: { lat: 40.4168, lng: -3.7038 },
  },
  {
    id: 'VIS-2026-007',
    customerId: 'CUS-107',
    customerName: 'Flors Barcelona',
    city: 'Barcelona',
    country: 'ES',
    scheduledAt: daysFromNow(8, 11, 0),
    status: 'PLANNED',
    salesRep: 'Ana Martins',
    notes: 'Negociação de desconto anual. Preparar análise de volume.',
    geo: { lat: 41.3851, lng: 2.1734 },
  },
  {
    id: 'VIS-2026-008',
    customerId: 'CUS-108',
    customerName: 'Bouquet Lisboa',
    city: 'Lisboa',
    country: 'PT',
    scheduledAt: daysFromNow(9, 15, 0),
    status: 'PLANNED',
    salesRep: 'Ana Martins',
    notes: 'Confirmação nova morada de entrega. Verificar espaço de armazenamento.',
    geo: { lat: 38.7223, lng: -9.1393 },
  },
  {
    id: 'VIS-2026-009',
    customerId: 'CUS-109',
    customerName: 'Fleur de Lis Cascais',
    city: 'Cascais',
    country: 'PT',
    scheduledAt: daysFromNow(11, 10, 0),
    status: 'PLANNED',
    salesRep: 'Pedro Silva',
    notes: 'Upsell coleção verão. Levar fichas técnicas Leucadendron.',
    geo: { lat: 38.6979, lng: -9.4215 },
  },
  {
    id: 'VIS-2026-010',
    customerId: 'CUS-110',
    customerName: 'Rosas & Rosas Setúbal',
    city: 'Setúbal',
    country: 'PT',
    scheduledAt: daysFromNow(13, 9, 0),
    status: 'PLANNED',
    salesRep: 'Tiago Sousa',
    notes: 'Visita de rotina trimestral.',
    geo: { lat: 38.5244, lng: -8.8882 },
  },
  {
    id: 'VIS-2026-011',
    customerId: 'CUS-111',
    customerName: 'Botânica Faro',
    city: 'Faro',
    country: 'PT',
    scheduledAt: daysFromNow(15, 10, 30),
    status: 'PLANNED',
    salesRep: 'Ana Martins',
    notes: 'Acompanhamento pós-incidente de entrega. Oferecer desconto fidelização.',
    geo: { lat: 37.0193, lng: -7.9304 },
  },
  {
    id: 'VIS-2026-012',
    customerId: 'CUS-112',
    customerName: 'El Jardín Valencia',
    city: 'Valencia',
    country: 'ES',
    scheduledAt: daysFromNow(17, 11, 0),
    status: 'PLANNED',
    salesRep: 'Pedro Silva',
    notes: 'Prospect novo. Recomendação de cliente atual em Madrid.',
    geo: { lat: 39.4699, lng: -0.3763 },
  },
  {
    id: 'VIS-2026-013',
    customerId: 'CUS-113',
    customerName: 'Pétalas & Sonhos Aveiro',
    city: 'Aveiro',
    country: 'PT',
    scheduledAt: daysFromNow(20, 14, 0),
    status: 'PLANNED',
    salesRep: 'Tiago Sousa',
    notes: 'Renovação stock antes do verão.',
    geo: { lat: 40.6405, lng: -8.6538 },
  },
  {
    id: 'VIS-2026-014',
    customerId: 'CUS-114',
    customerName: 'Flores del Sur Sevilla',
    city: 'Sevilla',
    country: 'ES',
    scheduledAt: daysFromNow(24, 9, 0),
    status: 'PLANNED',
    salesRep: 'Ana Martins',
    notes: 'Expansão para novo cliente no sul de Espanha.',
    geo: { lat: 37.3891, lng: -5.9845 },
  },
  {
    id: 'VIS-2026-015',
    customerId: 'CUS-115',
    customerName: 'Primavera Decorações Évora',
    city: 'Évora',
    country: 'PT',
    scheduledAt: daysFromNow(28, 10, 0),
    status: 'PLANNED',
    salesRep: 'Pedro Silva',
    notes: 'Primeira visita após regularização de fatura em atraso.',
    geo: { lat: 38.5714, lng: -7.9136 },
  },

  // ---- Históricas (20) -----------------------------------------------------
  {
    id: 'VIS-2026-016',
    customerId: 'CUS-101',
    customerName: 'Floricultura Lurdes',
    city: 'Porto',
    country: 'PT',
    scheduledAt: daysAgo(5, 9, 0),
    completedAt: daysAgo(5, 10, 30),
    status: 'DONE',
    salesRep: 'Tiago Sousa',
    notes: 'Visita produtiva. Encomenda de €1.200 fechada no local.',
    geo: { lat: 41.1579, lng: -8.6291 },
  },
  {
    id: 'VIS-2026-017',
    customerId: 'CUS-108',
    customerName: 'Bouquet Lisboa',
    city: 'Lisboa',
    country: 'PT',
    scheduledAt: daysAgo(7, 14, 0),
    completedAt: daysAgo(7, 15, 30),
    status: 'DONE',
    salesRep: 'Ana Martins',
    notes: 'Renovação de lista de preços aceite. Próxima visita em julho.',
    geo: { lat: 38.7223, lng: -9.1393 },
  },
  {
    id: 'VIS-2026-018',
    customerId: 'CUS-103',
    customerName: 'Jardim Secreto Braga',
    city: 'Braga',
    country: 'PT',
    scheduledAt: daysAgo(10, 11, 0),
    status: 'NO_SHOW',
    salesRep: 'Pedro Silva',
    notes: 'Cliente não estava disponível. Reagendado para próxima semana.',
    geo: { lat: 41.5518, lng: -8.4229 },
  },
  {
    id: 'VIS-2026-019',
    customerId: 'CUS-106',
    customerName: 'Verde Naranja Madrid',
    city: 'Madrid',
    country: 'ES',
    scheduledAt: daysAgo(12, 9, 30),
    completedAt: daysAgo(12, 11, 0),
    status: 'DONE',
    salesRep: 'Tiago Sousa',
    notes: 'Reunião positiva. Pedido de teste de nova linha Mediterranean Dry.',
    geo: { lat: 40.4168, lng: -3.7038 },
  },
  {
    id: 'VIS-2026-020',
    customerId: 'CUS-104',
    customerName: 'Daisy Florist Porto',
    city: 'Porto',
    country: 'PT',
    scheduledAt: daysAgo(14, 10, 0),
    completedAt: daysAgo(14, 11, 30),
    status: 'DONE',
    salesRep: 'Tiago Sousa',
    notes: 'Apresentação catálogo primavera. Encomenda €640 confirmada.',
    geo: { lat: 41.1496, lng: -8.6109 },
  },
  {
    id: 'VIS-2026-021',
    customerId: 'CUS-107',
    customerName: 'Flors Barcelona',
    city: 'Barcelona',
    country: 'ES',
    scheduledAt: daysAgo(15, 11, 0),
    completedAt: daysAgo(15, 13, 0),
    status: 'DONE',
    salesRep: 'Ana Martins',
    notes: 'Volume anual confirmado: ~€20k. Desconto 7% acordado pendente aprovação.',
    geo: { lat: 41.3851, lng: 2.1734 },
  },
  {
    id: 'VIS-2026-022',
    customerId: 'CUS-109',
    customerName: 'Fleur de Lis Cascais',
    city: 'Cascais',
    country: 'PT',
    scheduledAt: daysAgo(18, 10, 0),
    status: 'CANCELLED',
    salesRep: 'Pedro Silva',
    notes: 'Cancelada por Pedro (doença). Reagendada.',
    geo: { lat: 38.6979, lng: -9.4215 },
  },
  {
    id: 'VIS-2026-023',
    customerId: 'CUS-111',
    customerName: 'Botânica Faro',
    city: 'Faro',
    country: 'PT',
    scheduledAt: daysAgo(20, 10, 30),
    completedAt: daysAgo(20, 12, 0),
    status: 'DONE',
    salesRep: 'Ana Martins',
    notes: 'Cliente satisfeito com resolução do atraso. Nova encomenda €890.',
    geo: { lat: 37.0193, lng: -7.9304 },
  },
  {
    id: 'VIS-2026-024',
    customerId: 'CUS-113',
    customerName: 'Pétalas & Sonhos Aveiro',
    city: 'Aveiro',
    country: 'PT',
    scheduledAt: daysAgo(22, 14, 0),
    completedAt: daysAgo(22, 15, 30),
    status: 'DONE',
    salesRep: 'Tiago Sousa',
    notes: 'Stock de inverno liquidado. Interesse em produto mediterrânico.',
    geo: { lat: 40.6405, lng: -8.6538 },
  },
  {
    id: 'VIS-2026-025',
    customerId: 'CUS-102',
    customerName: 'Atelier Flora Coimbra',
    city: 'Coimbra',
    country: 'PT',
    scheduledAt: daysAgo(25, 10, 0),
    completedAt: daysAgo(25, 11, 45),
    status: 'DONE',
    salesRep: 'Ana Martins',
    notes: 'Discussão prévia contrato anual. Volumes confirmados.',
    geo: { lat: 40.2033, lng: -8.4103 },
  },
  {
    id: 'VIS-2026-026',
    customerId: 'CUS-110',
    customerName: 'Rosas & Rosas Setúbal',
    city: 'Setúbal',
    country: 'PT',
    scheduledAt: daysAgo(28, 9, 0),
    completedAt: daysAgo(28, 10, 15),
    status: 'DONE',
    salesRep: 'Tiago Sousa',
    notes: 'Visita trimestral de rotina. Feedback positivo sobre Pampas.',
    geo: { lat: 38.5244, lng: -8.8882 },
  },
  {
    id: 'VIS-2026-027',
    customerId: 'CUS-114',
    customerName: 'Flores del Sur Sevilla',
    city: 'Sevilla',
    country: 'ES',
    scheduledAt: daysAgo(30, 9, 0),
    completedAt: daysAgo(30, 11, 0),
    status: 'DONE',
    salesRep: 'Pedro Silva',
    notes: 'Primeiro encontro. Interesse em linha premium e produtos portugueses.',
    geo: { lat: 37.3891, lng: -5.9845 },
  },
  {
    id: 'VIS-2026-028',
    customerId: 'CUS-105',
    customerName: 'Florama Viseu',
    city: 'Viseu',
    country: 'PT',
    scheduledAt: daysAgo(35, 14, 0),
    completedAt: daysAgo(35, 15, 30),
    status: 'DONE',
    salesRep: 'Pedro Silva',
    notes: 'Apresentação geral. Encomenda inicial €320.',
    geo: { lat: 40.6566, lng: -7.9122 },
  },
  {
    id: 'VIS-2026-029',
    customerId: 'CUS-106',
    customerName: 'Verde Naranja Madrid',
    city: 'Madrid',
    country: 'ES',
    scheduledAt: daysAgo(40, 9, 30),
    completedAt: daysAgo(40, 11, 30),
    status: 'DONE',
    salesRep: 'Tiago Sousa',
    notes: 'Reunião comercial semestral. Novas condições acordadas.',
    geo: { lat: 40.4168, lng: -3.7038 },
  },
  {
    id: 'VIS-2026-030',
    customerId: 'CUS-108',
    customerName: 'Bouquet Lisboa',
    city: 'Lisboa',
    country: 'PT',
    scheduledAt: daysAgo(45, 14, 0),
    status: 'NO_SHOW',
    salesRep: 'Ana Martins',
    notes: 'Emergência familiar do cliente. Remarcado.',
    geo: { lat: 38.7223, lng: -9.1393 },
  },
  {
    id: 'VIS-2026-031',
    customerId: 'CUS-112',
    customerName: 'El Jardín Valencia',
    city: 'Valencia',
    country: 'ES',
    scheduledAt: daysAgo(50, 11, 0),
    completedAt: daysAgo(50, 12, 30),
    status: 'DONE',
    salesRep: 'Pedro Silva',
    notes: 'Visita de prospeção. Encomenda piloto acordada para junho.',
    geo: { lat: 39.4699, lng: -0.3763 },
  },
  {
    id: 'VIS-2026-032',
    customerId: 'CUS-101',
    customerName: 'Floricultura Lurdes',
    city: 'Porto',
    country: 'PT',
    scheduledAt: daysAgo(55, 9, 0),
    completedAt: daysAgo(55, 10, 30),
    status: 'DONE',
    salesRep: 'Tiago Sousa',
    notes: 'Balanço Q1. Crescimento 18% vs período homólogo.',
    geo: { lat: 41.1579, lng: -8.6291 },
  },
  {
    id: 'VIS-2026-033',
    customerId: 'CUS-104',
    customerName: 'Daisy Florist Porto',
    city: 'Porto',
    country: 'PT',
    scheduledAt: daysAgo(60, 10, 0),
    completedAt: daysAgo(60, 11, 15),
    status: 'DONE',
    salesRep: 'Tiago Sousa',
    notes: 'Visita rotina. Feedback positivo sobre entrega express.',
    geo: { lat: 41.1496, lng: -8.6109 },
  },
  {
    id: 'VIS-2026-034',
    customerId: 'CUS-107',
    customerName: 'Flors Barcelona',
    city: 'Barcelona',
    country: 'ES',
    scheduledAt: daysAgo(70, 9, 0),
    status: 'CANCELLED',
    salesRep: 'Ana Martins',
    notes: 'Ana em congresso. Reagendado para março.',
    geo: { lat: 41.3851, lng: 2.1734 },
  },
  {
    id: 'VIS-2026-035',
    customerId: 'CUS-115',
    customerName: 'Primavera Decorações Évora',
    city: 'Évora',
    country: 'PT',
    scheduledAt: daysAgo(80, 10, 0),
    completedAt: daysAgo(80, 11, 30),
    status: 'DONE',
    salesRep: 'Pedro Silva',
    notes: 'Acordo de pagamento a 30 dias estabelecido.',
    geo: { lat: 38.5714, lng: -7.9136 },
  },
];
